"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express = require("express");
var add_push_subscriber_route_1 = require("./add-push-subscriber.route");
var send_notification_route_1 = require("./send-notification.route");
var enrollment_service_route_1 = require("./enrollment-service.route");
var bodyParser = require('body-parser');
var webpush = require('web-push');
var cors = require('cors');

//const vapidKeysAutoGenerated = webpush.generateVAPIDKeys();
const vapidKeys = {
    "publicKey" : "BL8vx3ym0aZMrSr5nIMxw7rv3meD7AidviFiifbjG7fGJqeO72Nyzh7CaotVkhb4Lc3-WLZ0E-X5J-F-L5ZOecA",
    "privateKey" : "Womm_NColF4j4355lQRopy7lRQW3XTA_Vb2pTKQljSE"
}
//console.log(':'+vapidKeysAutoGenerated.publicKey+':');
//console.log(':'+vapidKeysAutoGenerated.privateKey+':');
webpush.setVapidDetails('mailto:vigneshsuryah.navyblue@gmail.com', vapidKeys.publicKey, vapidKeys.privateKey);
var app = express();
app.use(bodyParser.json());
app.use(cors({ origin: true, credentials: true }));
app.route('/api/enrollments')
    .post(enrollment_service_route_1.saveEnrollment);
app.route('/api/enrollments')
    .get(enrollment_service_route_1.getAllEnrollments);
app.route('/api/states')
    .get(enrollment_service_route_1.getAllStates);
app.route('/api/plans')
    .get(enrollment_service_route_1.getAllPlans);
app.route('/api/notifications')
    .post(add_push_subscriber_route_1.addPushSubscriber);
app.route('/api/notifications/enable')
    .post(send_notification_route_1.sendNotification);
app.route('/api/enrollments/clear')
    .get(enrollment_service_route_1.clearAllEnrollments);
//var PORT = 9000;
//var HOST = 'localhost';
//var httpServer = app.listen(PORT, PORT, function () {
//    console.log("HTTP Server running at http://" + HOST + ":" + PORT);
//});
app.listen(process.env.PORT || 5000);
